# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ddd051cb84a87ecd80bdd72fd1b3c4c3ccbf95d27807b76f01e87297b750e16daf6506c73b600bdc8d9f0f6263879242ba57bbbc46e80019bb7ddf489d51b2d

test:
  secret_key_base: 755abc2b9abb279d30a950c74982f7284f84d8f0d8432a8256dd3ff88bc5c67ad3570494bab2c1e249fe4ae5322f2ba101a622aa6cec6c77bd14b26449c96996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
